### ISSUE TITLE
Drag&drop bug under Linux X11

### ISSUE THREAD

**Issue by Ghost99** [myszha/qt-ponies#11]
Commit: 09d8f8524de84807112200f3971fe4bb47bb39cc
After dropping pony to other location it returning to the previous one.

Steps to reproduce:
1. Start dragging
2. Move somewhere
3. Release left mouse button (pony is still under the cursor)
4. Move cursor to one pixel or more -> pony immediately returning to previous location

**Comment by myszha** [comment]
I cannot reproduce this issue at my end, but hopefully this fix will resolve the problem.

**Comment by Ghost99** [comment]
Now drag&drop work correctly. Thanks.
