### ISSUE TITLE
Smaller ponies on the screen

### ISSUE THREAD

**Issue by fazek** [myszha/qt-ponies#12]
Dear Myszha,

Thank you for the Linux desktop ponies! I've added a quick solution to view everypony in half sizes. The default size was just too big and pixelated for me. I'm not very familiar with C++ and even less familiar in Qt so maybe my solution is ugly and not able to run on other systems. There is a "small ponies" switch in the settings menu. Perhaps a scaling slider would be better, but this is enough for me. You can find the diff file for your current master branch at:

https://github.com/fazek/qtponies-smallponies

My system is: Ubuntu 12.04 x86-64, Qt 4.8.1

Brohoof /)
fazek

**Comment by XRevan86** [comment]
Added in [this](https://bitbucket.org/XRevan86/poniesbox) fork.

**Comment by myszha** [comment]
Merged. Thanks for the effort, and XRevan86 for patching. For the future: use diff -u, because the default diff is hell to work with.

**Comment by XRevan86** [comment]
Great Maker, this project is active again :-).
Why mysha had [remove](https://github.com/myszha/qt-ponies/commit/d7c52d6fde6ab2130f01a50ab13d750ee8a9f6f6) link to openSUSE Software?

**Comment by myszha** [comment]
I thought it was a package for the forked version, so I removed it to not confuse anybody. As it is not the case, I've re-added the link. Thanks for noticing.
