### ISSUE TITLE
New ponies don't have preview

### ISSUE THREAD

**Issue by neonfuzz** [myszha/qt-ponies#13]
Feature Request:  More flexibility to add new ponies

I downloaded the latest pony pack from desktop ponies and replaced the qt-ponies library with the new library from desktop ponies.

( Desktop ponies download:  http://desktopponies.bugs3.com/viewtopic.php?f=1&t=3 )

This seems to work well, except that in the "Add Ponies" screen the new characters don't have a preview image and some older ponies that no longer exist still appear on the screen.

I think it would be great to see a feature to add/remove ponies and/or a feature to edit the pony menu entries to manually choose a preview image.

This could also be solved by updating the qt-pony library to the latest desktop ponies library, or at the very least adding Queen Chrysalis, which is my entire motivation for adding new ponies.

Thank you very much for this wonderful program.  It is so much fun; I love having ponies keep me company while I'm on my computer.

**Comment by myszha** [comment]
The preview images are stored as icon.png in the pony directory. So to have a preview icon, just save any image (e.g.: Chrysalis walking left) as 'icon.png' in the directory desktop-ponies/Chrysalis (or in whatever directory Chrysalis is in).

**Comment by neonfuzz** [comment]
Oh, fantastic!  That works perfectly; thanks!
