### ISSUE TITLE
Opening configuration with active ponies

### ISSUE THREAD

**Issue by Paulicus** [myszha/qt-ponies#14]
I just installed QT-ponies on Ubuntu 12.04. I noticed that trying to open the dialog via unity when any ponies are on the desktop causes all ponies to be duplicated, rather than opening the configuration window. Furthermore, the option for "Remove all Rainbow Dash," for example, only removed one of them, requiring every pony to be manually clicked and removed before the configuration window could be opened again.

**Comment by myszha** [comment]
It seems like you simply opened another instance of the program, as at this time it doesn't check if another instance is running. The configuration window is accesible from the system tray icon, but it seems like Unity invented its own way to do them. I'll see if I can add the Unity App indicator, but in the meanwhile you can whitelist qt-ponies to show up in the notification area: http://www.webupd8.org/2011/04/how-to-re-enable-notification-area.html (won't work in 13.04+)

Or (this is the preferred way) you can install the sni-qt package, it will make all QT System Tray icons show up in the notification area.

**Comment by Paulicus** [comment]
Thanks! It didn't seem to work for some reason, but I found that I can get
it open by launching from the terminal. Not sure why, but it works!

Paul

**Comment by Paulicus** [comment]
How exactly do I implement this? Should I just redownload the deb file and reinstall?

**Comment by myszha** [comment]
Just grab and install the newest (v0.9) release.

**Comment by Paulicus** [comment]
Is there an order to install the two files? I installed 'all' first and now
I can't install the AMD64.deb as it says the libstdc++6 dependency (>=4.8)
can't be satisfied. I tried removing the 'all data' but the issue persists.

Thank you for your help!
-Paul

**Comment by myszha** [comment]
Ubuntu 12.04 might have older libraries than I used to make the .deb with. You might have to build the program manually by installing the dependencies / developement libraries and compiling it. It would look something like this:

```
sudo apt-get install build-essential libx11-dev libxfixes-dev libqtcore4 libqtgui4 libqt4-dev qt4-qmake libqt4-network git
git clone https://github.com/myszha/qt-ponies/
cd qt-ponies
qmake
make
```

You then should have a qt-ponies binary in the qt-ponies directory.
