### ISSUE TITLE
Glitched Black Box from effects

### ISSUE THREAD

**Issue by ghost** [myszha/qt-ponies#5]
Hi, my first time on github. :)

I have a minor issue where a black box shows up when an effect is triggered, I've seen this happen in rainbow dash's rainboom effect and I can confirm this happens with other effects such as pinkie pie's sonic sneeze, the falling Tom rock, and applejack's apple tree. I am not sure how to attach a screenshot of what I am talking about so I uploaded screenshot if that helps? Here is the link to explain what I am saying:

((Link removed, as issue has been resolved.))

Compiled on macosx 10.7.4 lion, using macports gcc47 and nokia qt 4.8.2, using qmake from terminal.

Modified the makefile generated by qmake and added this in to the LIBS section:
(Perhaps needed for macosx users?)

-L/usr/X11/lib -I/usr/X11/include 

So then it looks like this:

LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -L/usr/X11/lib -I/usr/X11/include -lX11 -lXfixes -framework QtGui -framework QtCore 

This has to do with issue #4 being fixed, preventing qt-ponies from compiling on macosx without making this change to the generated makefile. After that, qt-ponies compiled successfully, but the issue with the black box around effects still persists, and I understand that you added preliminary effects support.

Again, just a minor issue I discovered.

**Comment by myszha** [comment]
I'm not sure if it will fix it, but try the newest commit.

The build problem should be fixed (as the X11 libs are not needed on OSX as far as I know).

**Comment by ghost** [comment]
Removing that line of text that from qt-ponies.pro that fixed issue #4 fixes the building problem without needing to add that line of text to the LIBS section to the generated makefile that I mentioned in my earlier post.

However, no changes to the makefile or qt-ponies.pro file results in this error:

g++ -headerpad_max_install_names -arch x86_64 -mmacosx-version-min=10.5 -o qt-ponies.app/Contents/MacOS/qt-ponies bin/main.o bin/pony.o bin/behavior.o bin/effect.o bin/speak.o bin/configwindow.o bin/csv_parser.o bin/interaction.o bin/debugwindow.o bin/moc_pony.o bin/moc_effect.o bin/moc_speak.o bin/moc_configwindow.o bin/moc_debugwindow.o bin/qrc_qt-ponies.o   -F/Library/Frameworks -L/Library/Frameworks -lX11 -lXfixes -framework QtGui -framework QtCore 
ld: library not found for -lX11
collect2: error: ld returned 1 exit status
make: **\* [qt-ponies.app/Contents/MacOS/qt-ponies] Error 1

So the change to remove the line of text in qt-ponies.pro from issue #4 was necessary for qt-ponies to compile.

The black box issue with the preliminary effects however must be an unrelated matter aside from a successful compilation.

Edit: I forgot to mention that I am using the newest commit.

**Comment by myszha** [comment]
Sorry, I forgot to push the changes to github.

**Comment by ghost** [comment]
I can confirm that the black effect window issue is fixed under OSX and that compiling has been successful without error! :)
