### ISSUE TITLE
Speech bubbles appear in task manager

### ISSUE THREAD

**Issue by creideiki** [myszha/qt-ponies#6]
Running under KDE 4.9.1 on Linux.

The ponies themselves don't appear in the task manager, which is as it should be. However, when a speech bubble appears, the bubble gets a task manager entry, called "qt-ponies" and with the same icon as the configuration window gets (looks like a default icon - an "X" with a circle arount the middle, not the same as the system tray icon). The task manager entry goes away again when the speech bubble disappears.

**Comment by myszha** [comment]
Setting the window type of the text label to Dock should skip the taskbar and pager. If this doesn't fix it, we'll have to do it manualy using Xlib I think.

**Comment by creideiki** [comment]
It looks fixed to me now.
