### ISSUE TITLE
New graphics don't stay on the same virtual desktop

### ISSUE THREAD

**Issue by creideiki** [myszha/qt-ponies#7]
Running under KDE 4.9.1 on Linux.

I have some ponies running on one virtual desktop, with "Show on every virtual desktop" disabled. The ponies stay on that virtual desktop. However, when new graphics appear (such as Applejack's tree or Derpy's letters), they show up on the currently active virtual desktop instead (with the pony staying on its original virtual desktop). They should be created on the same virtual desktop as their creating pony.

**Comment by myszha** [comment]
Simply assigning the parent window to the effects window and text labels fixes this problem as far as I can see (as Qt now knows on which desktop to show them).

**Comment by creideiki** [comment]
It looks fixed to me now.
