### ISSUE TITLE
Compile Error - OSX 10.8

### ISSUE THREAD

**Issue by ghost** [myszha/qt-ponies#9]
bash-3.2# make
g++ -c -pipe -std=c++0x -Wextra -flto -g -gdwarf-2 -arch x86_64 -mmacosx-version-min=10.5 -Wall -W -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -Isrc/moc -Isrc/ui -F/Library/Frameworks -o bin/pony.o src/pony.cpp
In file included from /Library/Frameworks/QtCore.framework/Headers/qnamespace.h:45:0,
                 from /Library/Frameworks/QtCore.framework/Headers/qobjectdefs.h:45,
                 from /Library/Frameworks/QtCore.framework/Headers/qobject.h:47,
                 from /Library/Frameworks/QtCore.framework/Headers/qcoreapplication.h:45,
                 from /Library/Frameworks/QtGui.framework/Versions/4/Headers/qapplication.h:45,
                 from /Library/Frameworks/QtGui.framework/Versions/4/Headers/QApplication:1,
                 from src/pony.cpp:19:
/Library/Frameworks/QtCore.framework/Headers/qglobal.h:328:6: warning: #warning "This version of Mac OS X is unsupported" [-Wcpp]
src/pony.cpp: In constructor 'Pony::Pony(QString, ConfigWindow_, QWidget_)':
src/pony.cpp:65:16: error: 'class ConfigWindow' has no member named 'getX11_WM'
src/pony.cpp:65:45: error: 'ConfigWindow::X11_WM_Types' has not been declared
make: **\* [bin/pony.o] Error 1

Hi, I have received the following error above when trying to compile.
I'm not certain if it has anything to do with Apple's version of X11 no longer being included as of 10.8, which in this case I have the latest XQuartz installed, if that information is helpful in some way.

Using Mac OSX 10.8.1 with XQuartz 2.7.3 and QT 4.8 and gcc47.

**Comment by myszha** [comment]
Should be fixed, I forgot to define out a X11 specific bit on non-X11 systems.

**Comment by ghost** [comment]
I can confirm that I am able to compile now. :)
